version: "3.9"

services:
  iris:
    container_name: sanitary-surveillance
    build:
      context: .
      dockerfile: Dockerfile
    image: sanitary-surveillance:latest
    init: true
    restart: unless-stopped
    volumes:
      - ./storage:/durable
      - ./:/opt/irisapp
    ports:
      - "52773:52773"  # IRIS Management Portal
      - "1972:1972"    # IRIS SuperServer
      - "8000:8000"    # API
      - "8501:8501"    # Streamlit Dashboard
    environment:
      - ISC_DATA_DIRECTORY=/durable/iris
    entrypoint: ["/opt/irisapp/entrypoint.sh"]
