services:
  iris:
    container_name: iris-sanitary-surveillance
    build:
      context: .       
      dockerfile: Dockerfile
    image: iris-sanitary-surveillance:latest 
    init: true
    restart: unless-stopped
    volumes:
      - ./storage:/durable
    ports:
      - "52773:52773"  
      - "1972:1972"  
    environment:
      - ISC_DATA_DIRECTORY=/durable/iris
    entrypoint: ["/opt/irisapp/entrypoint.sh"]